In [171]:
# 1)
smash = ['Mario', 'DK', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']
smash

['Mario', 'DK', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']

In [172]:
# 2)
smash.extend(['Luigi', 'Ness', 'C. Falcon', 'Jigglypuff'])
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff']

In [173]:
# 3)
smash.append(['Metal Mario', 'Polygon Team', 'Master Hand'])
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [174]:
# 4)
smash[0:8] = ['Original roster']
smash

['Original roster',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [175]:
# 5)
def null_matrix(m, n):
    return [[0 for i in range(n)] for i in range(m)]

null_matrix(3,4)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [176]:
# 6)
x, y, z = 4, 3, 2

[[['?' for i in range(z)] for i in range(y)] for i in range(x)]

[[['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']]]

In [177]:
# 7)
mensualidad = {
    'Disney+': 7,
    'Netflix': 8.99,
    'Prime':12.99
}

mensualidad

{'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}

In [178]:
# 8)
del mensualidad['Disney+']
mensualidad['Blim'] = 109
mensualidad['Netflix'] = 139
mensualidad['Prime'] = 99
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109}

In [179]:
# 9)
mensualidad['Tec'] = 20400
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109, 'Tec': 20400}

In [180]:
# 10)
import numpy as np

raw = np.ndarray((4,4), buffer=np.arange(1,17), dtype=np.int32)
raw

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [181]:
# 11)
raw[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [182]:
# 12)
raw[1:, 2:]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [183]:
# 13)
label = raw[:, 3]
features = raw[:, :3]

label, features

(array([ 4,  8, 12, 16]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]]))

In [184]:
# 14)
tuples = list(zip(features, label))

tuples

[(array([1, 2, 3]), 4),
 (array([5, 6, 7]), 8),
 (array([ 9, 10, 11]), 12),
 (array([13, 14, 15]), 16)]

In [185]:
# 15)
test = tuples[:1]
train = tuples[1:]

test, train

([(array([1, 2, 3]), 4)],
 [(array([5, 6, 7]), 8), (array([ 9, 10, 11]), 12), (array([13, 14, 15]), 16)])

## 16)
$70\% \cdot 35\% = 24.5%$

## 17)
$0.1\% \cdot 99\% = 0.099%$

## 18)
$f'(x) = 3x^2 \cos(x^2) - 2x^4 \sin(x^2)$

## 19)

f'(x) = $x^2\cos(x) + 2x\sin(x) + 4x^3$

## 20)

$\frac{\partial}{\partial x}f(x, z) = 3x^2 + 2xz + z^2$


$\frac{\partial}{\partial x \partial z}f(x, z) = 2x + 2z$